### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by AnimMouse** [jamiees2/commit#5]
I need internationalization support for this project. Will that ever be added?

**Comment by jamiees2** [comment]
What languages would you like to see added? The word `commit` is a requirement for this project to succeed

**Comment by AnimMouse** [comment]
If possible, all the languages as defined by ISO 639 are the ones I like to see added in order to have true internationalization support.

**Comment by jamiees2** [comment]
Could you provide an example of support for a different language (e.g Italian)?

I don't see myself undertaking this work in the near future, but would be happy to accept a PR that addresses this :)

**Comment by AnimMouse** [comment]
I have made an example at my [fork](https://github.com/AnimMouse/commit) that added en-GB translation.
